#!/usr/bin/env python3

import os, setproctitle
import configparser as _cp, time
import xml.etree.ElementTree as _et
# -- core --
from core.debug import debug
from core.utils import sysUtils as utils
from core.redisOps import redisOps
from core.logutils import logUtils
from modbus.modbusRedisRelay import modbusRedisRelay
from modbus.modbusEdgeMeters import modbusEdgeMeters
from modbus.ttydevMeters import ttydevMeters


"""
   bot steps:
      1. load ini file
      2. create redis ops object
      3. load register stream xml file: register_streams.xml  
      4. load data strucs for them
      5. create steam run-table
      6. main loop to check if it is time to run that stream
      7. if time is up ... run thread per stream
"""

cp: _cp = _cp.ConfigParser()
loaded: [] = cp.read("conf/modbus_redis_bot.ini")
if len(loaded) == 0:
   print("no ini files loaded")
   exit(1)

# -- -- -- -- load redis object  -- -- -- --
if debug.is_dev_box():
   redops = redisOps(cp, CONN_SEC="DEV_REDIS_CONN")
else:
   redops: redisOps = redisOps(cp)
# -- ping server --
if not redops.red.ping():
   print("UnableToPingRedisServer")
   exit(1)
#  -- -- -- -- -- -- -- -- -- -- -- -- -- --

"""
   reg_streams have timing attached to them
   register_streams.xml
"""
RS_XML_PATH: str = cp["METERS"]["REG_STREAMS_XML"]
if not os.path.exists(RS_XML_PATH):
   print(f"FileNotFound: {RS_XML_PATH}")
   exit(1)
RS_XML = _et.parse(RS_XML_PATH)

"""
   these are edge modbus based meters that can be grouped to multiple
   /dev/ttyUSBx devices under linux
   MM_XML_PATH is file with ALL modbus meters in the building grouped by 
   EDGE (HOST) -> ttyUSBx device 
"""
MM_XML_PATH: str = cp["METERS"]["MODBUS_METERS_XML"]
if not os.path.exists(MM_XML_PATH):
   print(f"FileNotFound: {MM_XML_PATH}")
   exit(1)
MM_XML = _et.parse(MM_XML_PATH).getroot()
# -- -- -- -- -- --
xpath: str = f"edges/edge[@hostname='{utils.HOST}']/ttydev"
ttydev_meters_arr: [ttydevMeters] = [ttydevMeters(n) for n in MM_XML.findall(xpath)]
for item in ttydev_meters_arr:
   item.init()
# -- -- -- -- -- --


"""
   -- -- -- -- run relay thread -- -- -- --
"""
time.sleep(2.0)
modbusRedisRelayTh: modbusRedisRelay = modbusRedisRelay(cp, redops, ttydev_meters_arr, RS_XML)
modbusRedisRelayTh.init()
modbusRedisRelayTh.start()


# -- main loop --
LOOP_SLEEP_SECS: float = float(cp["TIMING"]["LOOP_SLEEP_SECS"])

def main():
   setproctitle.setproctitle("modbusRedisBot")
   diag_tag: str = cp["SYSINFO"]["DIAG_TAG"]
   diag_tag = utils.diag_tag_prefix(diag_tag)
   while True:
      try:
         print("[ modbus_redis_bot: main ]")
         if True:
            msg = "modbusRedisRelay TRUE"
            dct: {} = {"bot_dts_utc": utils.dts_utc(), "msg": msg}
            modbusRedisRelayTh.redops.update_diag_tag(diag_tag=diag_tag, mapdct=dct, restart=False)
         # -- -- -- --
         time.sleep(LOOP_SLEEP_SECS)
      except Exception as e:
         logUtils.log_exp(e)


# -- -- -- ep -- -- --
if __name__ == "__main__":
   main()
