#!/bin/bash

#
# author: owsiak, erik
# date: 2023/01/12
#


echo ""
echo "  --[ START_START ]--"
echo ""

START_DIR=$(pwd)
MODBUS_START_FILE=conf/starts/modbus_redis_bot
MQTT_START_FILE=conf/starts/mqtt_redis_bot
PZEM_START_FILE=conf/starts/pzem_redis_bot

cd ..
START_FILES=("$MODBUS_START_FILE" "$MQTT_START_FILE" "$PZEM_START_FILE")
for f in "${START_FILES[@]}"; do
  if [ -f "$f" ]; then
    echo "WillStart: $f"
  else
    echo "WillNotStart: $f"
  fi
done

echo ""
echo ""
sleep 4
echo ""

: ' ---------------------------------------------------------------------------
  check: /etc/iotech for:
    building  ->  holds build ID - geoloc unique
    geoloc    ->  geolocation ex: gdn gda nyc waw
    systag    ->  system tag for host; used to prefix some reporting info
'
ETC_IOTECH="/etc/iotech"
CORE_FILES=("$ETC_IOTECH/building" "$ETC_IOTECH/geoloc" "$ETC_IOTECH/systag")
for f in "${CORE_FILES[@]}"; do
  if [ ! -f "$f" ]; then
    echo "NotFound: $f"
    exit 1
  else
    # shellcheck disable=SC2046
    echo " -> $f": $(more "$f")
  fi
done

: ' ---------------------------------------------------------------------------
  run setup_env
    1. create folder(s) /run/iotech/dev/
'
RUN_IOTECH="/run/iotech"
RUN_FOLDERS=("$RUN_IOTECH/omms" "$RUN_IOTECH/dev")
for d in "${RUN_FOLDERS[@]}"; do
  if [ ! -d "$d" ]; then
    mkdir -p "$d"
  else
    echo ""
    echo "[ FolderListing: $d ]"
    cd "$d" && ls "$d" -la
  fi
done

echo ""
echo "[ RUN_FOLDERS ]"
echo ""
for d in "${RUN_FOLDERS[@]}"; do
  if [ -d "$d" ]; then
    echo "PathFound: $d"
  else
    echo "PathNotFound: $d"
  fi
done


# 1. setup PYTHONPATH
cd "$START_DIR" && cd ..
PPATH=$(pwd)
export PYTHONPATH=$PPATH
echo ""
echo "PYTHONPATH: $PYTHONPATH"
echo ""

# 2. run ttydev discovery
killall -s KILL ttydevDiscoBot
PYFILE="bots/ttydev_discovery_bot"
# -- set x bit if not already --
chmod +x $PYFILE
# -- start bot --
$PYFILE
EXIT_CODE=$?

echo ""
echo "  -- [ EXIT_CODE: $EXIT_CODE FOR: $PYFILE ] --"
echo ""


# -------------------------------
# 3. start modbus bot
PYFILE="bots/modbus_redis_bot"
if [ -f $MODBUS_START_FILE ]; then
  # -- set x bit if not already --
  chmod +x $PYFILE
  # -- start bot --
  echo "- - -"
  echo "RUNNING PYFILE: $PYFILE"
  echo "- - -"
  $PYFILE >> /dev/null &
else
  echo ""
  echo "NotStarting: $PYFILE"
  echo ""
fi


# -------------------------------
# 4. start mqtt bot
PYFILE="bots/mqtt_redis_bot"
if [ -f $MQTT_START_FILE ]; then
  if [ ! -f $PYFILE ]; then
      echo "FileNotFound: $PYFILE"
      echo "Exiting..."
      exit 1
  fi
  # -- set x bit if not already --
  chmod +x $PYFILE
  # -- start bot --
  echo "- - -"
  echo "RUNNING PYFILE: $PYFILE"
  echo "- - -"
  $PYFILE >> /dev/null &
else
  echo ""
  echo "NotStarting: $PYFILE"
  echo ""
fi


# -------------------------------
# 5. start mqtt bot
PYFILE="bots/pzem_redis_bot"
if [ -f $PZEM_START_FILE ]; then
  if [ ! -f $PYFILE ]; then
      echo "FileNotFound: $PYFILE"
      echo "Exiting..."
      exit 1
  fi
  # -- set x bit if not already --
  chmod +x $PYFILE
  # -- start bot --
  echo "- - -"
  echo "RUNNING PYFILE: $PYFILE"
  echo "- - -"
  $PYFILE >> /dev/null &
else
  echo ""
  echo "NotStarting: $PYFILE"
  echo ""
fi

# -----------------------------------------------------------------------------
echo ""
echo "  --[ END_START ]--"
echo ""
